CREATE OR REPLACE FUNCTION F_LISTAR_CATEGORIAS
RETURN SYS_REFCURSOR
AS
  V_CURSOR SYS_REFCURSOR;
BEGIN
  OPEN V_CURSOR FOR
    SELECT * FROM CATEGORIA;
    
  RETURN V_CURSOR;
END F_LISTAR_CATEGORIAS;
/

CREATE OR REPLACE PROCEDURE SP_INSERTAR_CATEGORIA (
    P_NOMBRE VARCHAR2,
    P_DESCRIPCION VARCHAR2
)
AS
BEGIN
    INSERT INTO CATEGORIA (NOMBRE, DESCRIPCION)
    VALUES (P_NOMBRE, P_DESCRIPCION);
    COMMIT;
END SP_INSERTAR_CATEGORIA;
/

CREATE OR REPLACE FUNCTION F_ACTUALIZAR_CATEGORIA(
  P_ID_CATEGORIA NUMBER,
  P_NOMBRE VARCHAR2,
  P_DESCRIPCION VARCHAR2
) RETURN BOOLEAN
IS
  V_ACTUALIZADO BOOLEAN := FALSE;
BEGIN
  UPDATE CATEGORIA SET
    NOMBRE = P_NOMBRE,
    DESCRIPCION = P_DESCRIPCION
  WHERE ID_CATEGORIA = P_ID_CATEGORIA;

  IF SQL%ROWCOUNT = 1 THEN
    V_ACTUALIZADO := TRUE;
  END IF;

  RETURN V_ACTUALIZADO;
EXCEPTION
  WHEN OTHERS THEN
    RETURN FALSE;
END F_ACTUALIZAR_CATEGORIA;
/

CREATE OR REPLACE PROCEDURE SP_ELIMINAR_CATEGORIA (
    P_ID_CATEGORIA NUMBER
)
AS
BEGIN
    DELETE FROM CATEGORIA
    WHERE ID_CATEGORIA = P_ID_CATEGORIA;
    COMMIT;
END SP_ELIMINAR_CATEGORIA;
/

CREATE OR REPLACE PACKAGE PK_CATEGORIA AS
  FUNCTION F_LISTAR_CATEGORIAS RETURN SYS_REFCURSOR;
  PROCEDURE SP_INSERTAR_CATEGORIA(
    P_ID_CATEGORIA NUMBER,
    P_NOMBRE VARCHAR2,
    P_DESCRIPCION VARCHAR2
  );
  FUNCTION F_ACTUALIZAR_CATEGORIA(
    P_ID_CATEGORIA NUMBER,
    P_NOMBRE VARCHAR2,
    P_DESCRIPCION VARCHAR2
  ) RETURN BOOLEAN;
  PROCEDURE SP_ELIMINAR_CATEGORIA(
    P_ID_CATEGORIA NUMBER
  );
END PK_CATEGORIA;
/

CREATE TABLE AUDITORIA_CATEGORIA (
  ID_CATEGORIA NUMBER(11,0),
  NOMBRE VARCHAR2(50),
  DESCRIPCION VARCHAR2(100),
  OPERACION VARCHAR2(6),
  FECHA_OPERACION DATE
);

CREATE OR REPLACE TRIGGER TRG_CATEGORIA_INSERT
AFTER INSERT ON CATEGORIA
FOR EACH ROW
BEGIN
  INSERT INTO AUDITORIA_CATEGORIA (ID_CATEGORIA, NOMBRE, DESCRIPCION, OPERACION, FECHA_OPERACION)
  VALUES (:NEW.ID_CATEGORIA, :NEW.NOMBRE, :NEW.DESCRIPCION, 'INSERT', SYSDATE);
END;
/

CREATE OR REPLACE TRIGGER TRG_CATEGORIA_UPDATE
AFTER UPDATE ON CATEGORIA
FOR EACH ROW
BEGIN
  INSERT INTO AUDITORIA_CATEGORIA (ID_CATEGORIA, NOMBRE, DESCRIPCION, OPERACION, FECHA_OPERACION)
  VALUES (:OLD.ID_CATEGORIA, :OLD.NOMBRE, :OLD.DESCRIPCION, 'UPDATE', SYSDATE);
END;
/

CREATE OR REPLACE TRIGGER TRG_CATEGORIA_DELETE
AFTER DELETE ON CATEGORIA
FOR EACH ROW
BEGIN
  INSERT INTO AUDITORIA_CATEGORIA (ID_CATEGORIA, NOMBRE, DESCRIPCION, OPERACION, FECHA_OPERACION)
  VALUES (:OLD.ID_CATEGORIA, :OLD.NOMBRE, :OLD.DESCRIPCION, 'DELETE', SYSDATE);
END;
/
