CREATE OR REPLACE FUNCTION F_LISTAR_COLABORADORES
RETURN SYS_REFCURSOR
AS
  V_CURSOR SYS_REFCURSOR;
BEGIN
  OPEN V_CURSOR FOR
    SELECT * FROM COLABORADORES;
    
  RETURN V_CURSOR;
END F_LISTAR_COLABORADORES;

CREATE OR REPLACE PROCEDURE SP_INSERTAR_COLABORADOR (
    P_CEDULA_COLABORADOR VARCHAR2,
    P_NOMBRE VARCHAR2,
    P_APELLIDO_1 VARCHAR2,
    P_APELLIDO_2 VARCHAR2,
    P_CORREO VARCHAR2,
    P_TELEFONO VARCHAR2,
    P_PUESTO VARCHAR2,
    P_COL_DIRECCION VARCHAR2
)
AS
BEGIN
    INSERT INTO COLABORADORES (CEDULA_COLABORADOR, NOMBRE, APELLIDO_1, APELLIDO_2, CORREO, TELEFONO, PUESTO, COL_DIRECCION)
    VALUES (P_CEDULA_COLABORADOR, P_NOMBRE, P_APELLIDO_1, P_APELLIDO_2, P_CORREO, P_TELEFONO, P_PUESTO, P_COL_DIRECCION);
    COMMIT;
END SP_INSERTAR_COLABORADOR;

CREATE OR REPLACE FUNCTION F_ACTUALIZAR_COLABORADOR(
  P_ID_COLABORADOR NUMBER,
  P_CEDULA_COLABORADOR VARCHAR2,
  P_NOMBRE VARCHAR2,
  P_APELLIDO_1 VARCHAR2,
  P_APELLIDO_2 VARCHAR2,
  P_CORREO VARCHAR2,
  P_TELEFONO VARCHAR2,
  P_PUESTO VARCHAR2,
  P_COL_DIRECCION VARCHAR2
) RETURN BOOLEAN
IS
  V_ACTUALIZADO BOOLEAN := FALSE;
BEGIN
  UPDATE COLABORADORES SET
    CEDULA_COLABORADOR = P_CEDULA_COLABORADOR,
    NOMBRE = P_NOMBRE,
    APELLIDO_1 = P_APELLIDO_1,
    APELLIDO_2 = P_APELLIDO_2,
    CORREO = P_CORREO,
    TELEFONO = P_TELEFONO,
    PUESTO = P_PUESTO,
    COL_DIRECCION = P_COL_DIRECCION
  WHERE ID_COLABORADOR = P_ID_COLABORADOR;

  IF SQL%ROWCOUNT = 1 THEN
    V_ACTUALIZADO := TRUE;
  END IF;

  RETURN V_ACTUALIZADO;
EXCEPTION
  WHEN OTHERS THEN
    RETURN FALSE;
END F_ACTUALIZAR_COLABORADOR;

CREATE OR REPLACE PROCEDURE SP_ELIMINAR_COLABORADOR (
    P_ID_COLABORADOR NUMBER
)
AS
BEGIN
    DELETE FROM COLABORADORES
    WHERE ID_COLABORADOR = P_ID_COLABORADOR;
    COMMIT;
END SP_ELIMINAR_COLABORADOR;

CREATE OR REPLACE PACKAGE PK_Colaboradores
IS
  FUNCTION F_LISTAR_COLABORADORES RETURN SYS_REFCURSOR;
  PROCEDURE SP_INSERTAR_COLABORADOR (
    P_ID_COLABORADOR NUMBER,
    P_CEDULA_COLABORADOR VARCHAR2,
    P_NOMBRE VARCHAR2,
    P_APELLIDO_1 VARCHAR2,
    P_APELLIDO_2 VARCHAR2,
    P_CORREO VARCHAR2,
    P_TELEFONO VARCHAR2,
    P_PUESTO VARCHAR2,
    P_COL_DIRECCION VARCHAR2
  );
  FUNCTION F_ACTUALIZAR_COLABORADOR(
    P_ID_COLABORADOR NUMBER,
    P_CEDULA_COLABORADOR VARCHAR2,
    P_NOMBRE VARCHAR2,
    P_APELLIDO_1 VARCHAR2,
    P_APELLIDO_2 VARCHAR2,
    P_CORREO VARCHAR2,
    P_TELEFONO VARCHAR2,
    P_PUESTO VARCHAR2,
    P_COL_DIRECCION VARCHAR2
  ) RETURN BOOLEAN;
  PROCEDURE SP_ELIMINAR_COLABORADOR (
    P_ID_COLABORADOR NUMBER
  );
END PK_Colaboradores;

CREATE TABLE AUDITORIA_COLABORADORES (
  ID_COLABORADOR NUMBER(11,0),
  CEDULA_COLABORADOR VARCHAR2(10),
  NOMBRE VARCHAR2(50),
  APELLIDO_1 VARCHAR2(50),
  APELLIDO_2 VARCHAR2(50),
  CORREO VARCHAR2(100),
  TELEFONO VARCHAR2(20),
  PUESTO VARCHAR2(50),
  COL_DIRECCION VARCHAR2(100),
  OPERACION VARCHAR2(6),
  FECHA_OPERACION DATE
);

CREATE OR REPLACE TRIGGER TRG_COLABORADORES_INSERT
AFTER INSERT ON COLABORADORES
FOR EACH ROW
BEGIN
  INSERT INTO AUDITORIA_COLABORADORES (ID_COLABORADOR, CEDULA_COLABORADOR, NOMBRE, APELLIDO_1, APELLIDO_2, CORREO, TELEFONO, PUESTO, COL_DIRECCION, OPERACION, FECHA_OPERACION)
  VALUES (:NEW.ID_COLABORADOR, :NEW.CEDULA_COLABORADOR, :NEW.NOMBRE, :NEW.APELLIDO_1, :NEW.APELLIDO_2, :NEW.CORREO, :NEW.TELEFONO, :NEW.PUESTO, :NEW.COL_DIRECCION, 'INSERT', SYSDATE);
END;

CREATE OR REPLACE TRIGGER TRG_COLABORADORES_UPDATE
AFTER UPDATE ON COLABORADORES
FOR EACH ROW
BEGIN
  INSERT INTO AUDITORIA_COLABORADORES (ID_COLABORADOR, CEDULA_COLABORADOR, NOMBRE, APELLIDO_1, APELLIDO_2, CORREO, TELEFONO, PUESTO, COL_DIRECCION, OPERACION, FECHA_OPERACION)
  VALUES (:OLD.ID_COLABORADOR, :OLD.CEDULA_COLABORADOR, :OLD.NOMBRE, :OLD.APELLIDO_1, :OLD.APELLIDO_2, :OLD.CORREO, :OLD.TELEFONO, :OLD.PUESTO, :OLD.COL_DIRECCION, 'UPDATE', SYSDATE);
END;

CREATE OR REPLACE TRIGGER TRG_COLABORADORES_DELETE
AFTER DELETE ON COLABORADORES
FOR EACH ROW
BEGIN
  INSERT INTO AUDITORIA_COLABORADORES (ID_COLABORADOR, CEDULA_COLABORADOR, NOMBRE, APELLIDO_1, APELLIDO_2, CORREO, TELEFONO, PUESTO, COL_DIRECCION, OPERACION, FECHA_OPERACION)
  VALUES (:OLD.ID_COLABORADOR, :OLD.CEDULA_COLABORADOR, :OLD.NOMBRE, :OLD.APELLIDO_1, :OLD.APELLIDO_2, :OLD.CORREO, :OLD.TELEFONO, :OLD.PUESTO, :OLD.COL_DIRECCION, 'DELETE', SYSDATE);
END;