# Generated by Django 4.1.7 on 2023-04-17 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0005_alter_categoria_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'managed': False},
        ),
    ]
