# Generated by Django 4.1.7 on 2023-03-28 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('codigo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=56)),
                ('creditos', models.PositiveBigIntegerField()),
            ],
        ),
    ]
