# Generated by Django 4.1.7 on 2023-03-29 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0004_alter_curso_codigo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'managed': True},
        ),
    ]
